version: "3"

services:
  db:
    build: .
    container_name: "SPCFcon"
    ports:
      - "3307:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - volumedb:/vol

volumes:
  volumedb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device:
