version: "3"

services:
  mongo:
    build: "mongodbdock/."
    container_name: "SPFCmongo"
    ports:
      - "27022:27017"
    cap_add:
      - SYS_NICE
    volumes:
      - "./vol:/vol"
  mysql:
    build: "mysqldock/."
    container_name: "SPFCmysql"
    ports:
      - "3307:3306"
    volumes:
      - "./scripts/setup.sql:/docker-entrypoint-initdb.d/myspfc.sql"

